### ISSUE TITLE
Document a [non-iframe] embedded resource flow

### ISSUE THREAD

**Issue by myok12** [cfredric/storage-access-headers#4]
IIUC, with the proposed header/s implemented, other resources such as js, css, img can be directly embedded in otherwise-cookie-partitioned sites, as the proposed header/s satisfy the embedee's opt-in, obviating the `requestStorageAccess` js call from the embedee and an iframe. The proposal should walk through one such example.

**Comment by cfredric** [comment]
I've added a basic example for this in 57147ac; tentatively closing this, feel free to reopen if that doesn't address what you're looking for.
